### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by pranavlathigara** [PedramDarapanah/xml2code#1]
Got Error Null Reference Exception while drag layout file on application

**Comment by PedramDarapanah** [comment]
Thanks for your report.
I forgot to ignore the <?xml> tag at the beginning of the layout file

**Comment by pranavlathigara** [comment]
still not working.... 
getting same error...

**Comment by PedramDarapanah** [comment]
hi.
thanks for reporting me again.
would you please send  me the XML file you are testing ?

On Thu, Jun 18, 2015 at 11:31 AM, Pranav Lathigara <notifications@github.com

**Comment by pranavlathigara** [comment]
its  say copied to clipboard
